$lines = @(
  'Local 9Router targets:'
  '  make install          Install npm deps (repo root + cli).'
  '  make build            Build CLI bundle to cli/app (no deploy).'
  '  make deploy           Copy cli/app into installed 9router; stop/restart if running.'
  '  make release          Test, build, backup, replace, restart, and health-check.'
  '  make release-strict   Same, but rollback unless cu/default returns real content.'
  '  make release-no-test  Skip unit tests; build and deploy (not recommended).'
  '  make release-dry-run  Print the release plan without changing anything.'
  '  make release-check    Validate script syntax and run the dry-run preflight.'
  '  make deploy-dry-run   Print the deploy plan without changing anything.'
  ''
  'Step by step (Windows / macOS / Linux):'
  '  1. make install                                          (first time only)'
  '  2. make release                                          (test + build + deploy)'
  '  OR split build and deploy:'
  '     make build'
  '     make deploy'
  '  3. make deploy fails if cli/app is missing - run make release or make build first'
  '  4. Data preserved at ~/.9router or %USERPROFILE%\.9router'
  ''
  'macOS / Linux overrides:'
  '  INSTALL_DIR=$(npm root -g)/9router  NODE_BIN=$(which node)'
  ''
  'Windows note: make uses PowerShell scripts (no bash/WSL required).'
  '  INSTALL_DIR is auto-detected via npm root -g\9router'
)

foreach ($line in $lines) { Write-Host $line }
